artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion

data_prepare:
  train_images: artifacts/data_ingestion/train-images-idx3-ubyte
  train_labels: artifacts/data_ingestion/train-labels-idx1-ubyte
  test_images: artifacts/data_ingestion/t10k-images-idx3-ubyte
  test_labels: artifacts/data_ingestion/t10k-labels-idx1-ubyte

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/model.h5

training:
  root_dir: artifacts/training
  base_model_path: artifacts/base_model/model.h5
  trained_model_path: artifacts/training/model.h5